namespace BohemiX.Core.Models.Saves;

/// <summary>
/// Logical save slot record. PhysicalName is generated by the system; DisplayName is user-facing only.
/// </summary>
public sealed record SaveSlot(
    Guid Id,
    string PhysicalName,
    string DisplayName,
    string PhysicalPath,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    string? GameSaveName,
    TimeSpan? PlayTime,
    DateTimeOffset? LastSavedAtUtc,
    DisplayInfo? DisplayData = null,
    SaveType? Type = null,
    string? GameVersion = null,
    string? ThumbnailPath = null);
