namespace BohemiX.Modules.SaveManager.Models;

public sealed record SaveManagerText(
    string Title,
    string Subtitle,
    string NewProfile,
    string Import,
    string OpenVault,
    string Refresh,
    string ActiveProfile,
    string Profiles,
    string Snapshots,
    string Safety,
    string Safe,
    string Unsafe,
    string UnmanagedTitle,
    string UnmanagedBody,
    string ManageCurrent,
    string SearchWatermark,
    string FilterAll,
    string FilterFavorites,
    string FilterActive,
    string SortRecent,
    string SortName,
    string SortUpdated,
    string ProfileName,
    string QuestLocation,
    string PlayTime,
    string SavedAt,
    string NoProfilesTitle,
    string NoProfilesBody,
    string InspectorEmpty,
    string InUse,
    string SwitchProfile,
    string Rename,
    string Favorite,
    string Unfavorite,
    string OpenFolder,
    string Delete,
    string Metadata,
    string Quest,
    string Location,
    string Level,
    string GameVersion,
    string SnapshotHistory,
    string CreateSnapshot,
    string Restore,
    string Export,
    string NoSnapshots,
    string Working,
    string Ready,
    string TriggerManual,
    string TriggerBeforeSwitch,
    string TriggerGameExit,
    string TriggerBeforeRestore,
    string CloneTitle,
    string ClonePrompt,
    string RenameTitle,
    string RenamePrompt,
    string DeleteProfileTitle,
    string DeleteProfileMessage,
    string DeleteSnapshotTitle,
    string DeleteSnapshotMessage,
    string RestoreTitle,
    string RestoreMessage,
    string Cancel,
    string Confirm,
    string Save,
    string ErrorTitle,
    string ContinueGame,
    string ContinueGameHint,
    string GameLaunchRequested,
    string GameLaunchFailed,
    string ProfileSwitchedLaunchFailed,
    string CurrentModConfiguration,
    string CurrentModConfigurationFormat,
    string ModConfigurationUnavailable,
    string CharacterStatus,
    string Groschen,
    string StatusEffects,
    string NoStatusEffects,
    string More,
    string SaveTypePotion,
    string SaveTypeBed,
    string SaveTypeAuto,
    string SaveTypeExit,
    string SaveTypeUnknown,
    string LocationUnknown,
    string ThumbnailUnavailable,
    string ProfileManagement,
    string GameSaveFile)
{
    public static SaveManagerText ForLanguage(string? language) =>
        string.Equals(language, "English", StringComparison.OrdinalIgnoreCase) ? English : Chinese;

    public static SaveManagerText Chinese { get; } = new(
        "存档管理", string.Empty,
        "新建", "导入", "目录", "刷新", "当前", "档案", "快照", "切换",
        "可切换", "游戏运行中", "未纳管存档", "官方目录里有存档。先纳入管理再切换。", "纳入管理",
        "搜索档案 / 任务 / 地点", "全部", "收藏", "使用中", "最近", "名称", "更新",
        "档案", "任务 / 地点", "时长", "保存于", "暂无档案", "新建档案，或导入 .bohemix-save.zip。",
        "选择档案查看详情。", "使用中", "切换到此档案", "改名", "收藏", "取消收藏", "打开目录", "删除",
        "摘要", "任务", "地点", "等级", "版本", "快照", "创建快照", "恢复", "导出", "无快照", "处理中…", "就绪",
        "手动", "切换前", "退出", "恢复前", "新建档案", "输入名称；将完整克隆当前档案。",
        "重命名", "仅改显示名。", "删除档案", "将删除档案及全部快照，不可撤销。",
        "删除快照", "将永久删除所选快照。", "恢复快照", "会覆盖当前内容；先自动做安全快照。",
        "取消", "确认", "保存", "失败",
        "继续游戏", "切换档案并启动", "已请求启动", "启动失败，检查安装与 Mod", "档案已切换，但启动失败",
        "Mod 配置", "已启用 {0} 个 Mod", "配置不可用", "角色", "格罗申", "状态", "无状态", "更多",
        "手动", "睡眠", "自动", "退出", "存档", "未知地点", "无预览", "档案", "游戏存档");

    public static SaveManagerText English { get; } = new(
        "Saves", string.Empty,
        "New", "Import", "Folder", "Refresh", "Active", "Profiles", "Snapshots", "Switch",
        "Ready", "Game running", "Unmanaged save", "Official folder has saves. Manage them before switching.", "Manage",
        "Search profiles / quests / places", "All", "Favorites", "Active", "Recent", "Name", "Updated",
        "Profile", "Quest / Location", "Play time", "Saved", "No profiles", "Create a profile or import a .bohemix-save.zip.",
        "Select a profile.", "Active", "Switch here", "Rename", "Favorite", "Unfavorite", "Folder", "Delete",
        "Summary", "Quest", "Location", "Level", "Version", "Snapshots", "Snapshot", "Restore", "Export", "No snapshots", "Working…", "Ready",
        "Manual", "Pre-switch", "Exit", "Pre-restore", "New profile", "Name it; clones the selected profile.",
        "Rename", "Display name only.", "Delete profile", "Deletes the profile and all snapshots. Cannot undo.",
        "Delete snapshot", "Permanently deletes this snapshot.", "Restore snapshot", "Overwrites current content after a safety snapshot.",
        "Cancel", "Confirm", "Save", "Failed",
        "Continue", "Switch profile and launch", "Launch requested", "Launch failed. Check install and mods.", "Profile switched; launch failed.",
        "Mod loadout", "{0} mods enabled", "Unavailable", "Character", "Groschen", "Status", "None", "More",
        "Manual", "Sleep", "Auto", "Exit", "Save", "Unknown", "No preview", "Profile", "Game save");
}
