using System.Collections.Generic;

namespace BohemiX.Core.Models;

public sealed record AppSettings(
    string? PreferredGameInstallPath,
    string? PreferredGameExecutablePath,
    string ModsDirectory,
    bool AllowNexusBrowserCookieAuth = false,
    string SelectedLanguage = "简体中文",
    string DefaultNavigationTarget = "Dashboard",
    bool ShowNavigationTooltips = true,
    bool KeepTopNavigationVisible = true,
    bool AutoDiscoverOnStartup = true,
    bool EnableVfsBeforeLaunch = true,
    string LaunchArguments = "",
    bool UseSteamProtocol = false,
    bool MinimizeOnLaunch = false,
    bool CloseAfterLaunch = false,
    bool CheckModConflictsBeforeLaunch = true,
    bool EnableAcrylicEffects = true,
    bool ReduceMotion = false,
    double BackgroundDimLevel = 68,
    bool CompactSidebar = false,
    bool ShowRuntimeCardInSidebar = true,
    string? OfficialSavePath = null,
    bool AutoSnapshotOnGameExit = true,
    bool AutoSnapshotBeforeSwitch = true,
    int AutoSnapshotRetention = 20,
    bool AutoBackupSaveNodes = true,
    int BackupNodeRetention = 10,
    bool AutoMarkCriticalSaveNodesImportant = true,
    bool AutoMarkManualSaveNodesImportant = true,
    IReadOnlyDictionary<string, string>? InstalledModGroupNames = null,
    IReadOnlyDictionary<string, string>? InstalledModGroupAssignments = null,
    string? StaticBackgroundPath = null,
    string? DynamicBackgroundPath = null,
    bool UseDynamicBackground = false,
    int BackgroundCropMode = 0,
    double BackgroundCropX = 0,
    double BackgroundCropY = 0,
    double BackgroundCropWidth = 1,
    double BackgroundCropHeight = 1,
    string? CardBackgroundPath = null,
    bool UseDynamicCardBackground = false,
    string? StaticCardBackgroundPath = null,
    string? DynamicCardBackgroundPath = null,
    string ForgeRenderQuality = "Medium",
    string ForgeTextureQuality = "Medium");
